version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107-ff106
    working_directory: ~/repo

jobs:
  run-tests:
    executor: cypress-executor
    steps:
      - checkout
      - run: npm ci
      - run: npx cypress run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  test:
    jobs:
      - run-tests
